"""Scene graph -> Photoshop script (.jsx) that builds the layered PSD.

Photoshop sets the text, so real Gibson comes from the designer's own Adobe
Fonts activation, and the product is the full-res TIFF from their disk. The
scene is embedded as a JS literal (ExtendScript has no JSON.parse).
"""
from __future__ import annotations

import json
from pathlib import Path

LIB = Path(__file__).with_name("ps_builder.jsx")


def to_jsx(scene: dict, out_name: str, root: Path | None = None) -> str:
    """root: project root, to embed image assets (the can artwork) as base64.

    Everything is emitted as short lines (ExtendScript's parser is old; very long
    lines and exotic literals are where it breaks).
    """
    import base64
    data = json.dumps({"scene": scene, "out_name": out_name}, ensure_ascii=True, indent=0)
    parts = ["#target photoshop",
             f"// Generated by dimcomp for {scene['meta']['sku']}. In Photoshop: File > Scripts > Browse...",
             f"// Keep this file next to {Path(_product(scene)['src']).name} (or pick it when asked).",
             "var DATA = " + data + ";",
             "DATA.assets = {};"]
    for layer in _walk(scene["layers"]):
        if layer.get("asset") and root is not None:
            b64 = base64.b64encode((root / layer["src"]).read_bytes()).decode()
            chunks = ",\n".join(f'"{b64[i:i + 1000]}"' for i in range(0, len(b64), 1000))
            parts.append(f'DATA.assets["{layer["src_name"]}"] = [\n{chunks}\n].join("");')
    return "\n".join(parts) + "\n" + LIB.read_text()


def _product(scene: dict) -> dict:
    return next(l for l in scene["layers"] if l["id"] == "product")


def _walk(layers):
    for l in layers:
        yield l
        if l.get("type") == "group":
            yield from _walk(l["children"])
